version: '3.9'

services:
  postgres:
    image: postgres:17
    container_name: postgres_db_proj2_1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql  # Mount the init script here
    ports:
      - "5432:5432"
    networks:
      - db_network

networks:
  db_network:
